### ISSUE TITLE
Publish node package 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-aave-v3#814]
Publish a package npm for integrators

**Comment by Rubilmax** [comment]
For an integrator using our hypothetical npm package, they will be forced to write custom remappings to match our imports. So technically, it is as complex for them as to use this repository as a submodule and write remappings for our imports to either their submodules, or their node modules. For this reason, it's not interesting to publish an npm package.
Next time, if this is important for integrators, we need to name our remappings based on the associated node modules.
