### ISSUE TITLE
Fix CI again

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-aave-v3#819]
### 1
https://github.com/morpho-org/morpho-aave-v3/actions/runs/4894870159/jobs/8739741536?pr=783
PR: https://github.com/morpho-org/morpho-aave-v3/pull/783

### 2
https://github.com/morpho-org/morpho-aave-v3/actions/runs/4934925126/jobs/8820628943?pr=823
PR: https://github.com/morpho-org/morpho-aave-v3/pull/823

**Comment by Rubilmax** [comment]
It seems these were already fixed in #800
