### ISSUE TITLE
`RewardsManager` in the `extensions` folder?

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-aave-v3#824]
It's not strictly part of the protocol, so I was wondering what is the best place for it

**Comment by Rubilmax** [comment]
It depends on how being part of the protocol is defined: if it's defined as all the contracts called by Morpho, then it is (because the RewardsManager is called at every interaction)

**Comment by MathisGD** [comment]
"extension" seems good for the RewardsManager, but then it seems less good for the vaults (which are much more periphery or external than extensions)
