### ISSUE TITLE
Move from `_getAssetIndex` to `rewardsController.getAssetIndex()`?

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-aave-v3#827]
This is what is used here: https://github.com/bgd-labs/static-a-token-v3/blob/40d1a870c95e9a550f47d422d91a76ce43b55263/src/StaticATokenLM.sol#L277-L283

But I'm not sure that this is what we should do

**Comment by Rubilmax** [comment]
I'd rather suggest to return `(localRewardData.index, _REWARDS_CONTROLLER.getAssetIndex)` inside `_getAssetIndex`. But it seems to be something more relative to an optimization, rather than necessary.

**Comment by MerlinEgalite** [comment]
Better not to change the codebase that is working already
