### ISSUE TITLE
[Bulker UX] wrap and unwrap amount with a withdraw / repay

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/morpho-aave-v3#843]
## Situation
Morpho is a lending protocol accruing interests at each block. So the balance of a collateral / debt is hard to know in advance, even impossible since you have to know the timestamp of the block including the tx.

The problem comes when you want to do actions after a max withdraw/repay with the retrieved tokens.

For example, Alice wants to withdraw all her wstEth collateral and unwrap everything. To withdraw, we are just going to call withdraw(wstEth, address(bulker), type(u256).max). The bulker has now all the collateral. And what is the amount to unwrap?

Another example, Bob wants to repay all his weth debt with native eth. So we send eth to the contract, the bulker wrap all the balance needed to repay with a buffer (to repay the interests accrued since the last amount was computed). so Morpho is going to take only the needed balance. This behavior leads to a small amount of weth remaining in the bulker. We can call skim(wEth), but a repay with a native eth leads to a transfer of wEth to Bob, which is not expected at all. With the current implémentation, we cannot do anything else.

Another example, we know that wrapping and unwrapping stEth can lead to 1 wei less. So the supply from a stEth can only be done by letting potentially 1 wei of wstEth in the bulker, which is not really clean as an onchain implementation

### Do nothing
We let some dust in the bulker in case of a max withdraw etc. This can lead to unexpected reverts if balances computed are not fully accrued.

### Add a max limiter
Limit the amounts with the balance of the bulker.

Let's take the example of the `_unwrapStEth` function:

```solidity
    function _unwrapStEth(bytes calldata data) internal {
        (uint256 amount, address receiver) = abi.decode(data, (uint256, address));

        amount = Math.min(amount, ERC20(_WST_ETH).balanceOf(address(this)));

        if (amount == 0) revert AmountIsZero();
        if (receiver == address(this)) revert TransferToSelf();


        uint256 unwrapped = IWSTETH(_WST_ETH).unwrap(amount);

        ERC20(_ST_ETH).safeTransfer(receiver, unwrapped);
    }
```

That also permits to homogenize the behavior with the one of Morpho where the withdraw//repay are maximized by the balance of the user

**Comment by Rubilmax** [comment]
Using `Math.min(amount, balanceOf)` seems ok to me, given anyone is already able to sweep tokens from the router in a separate tx
